apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: blog-backend-monitor
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: blog-backend
  namespaceSelector:
    matchNames:
      - blog-app
  endpoints:
    - port: backend-port
      path: /metrics
      interval: 15s
