apiVersion: v1
kind: Secret
metadata:
  name: blog-api-secrets
  namespace: default
type: Opaque
stringData:
  # Paste your connection string from MongoDB Atlas here
  MONGODB_URI: "mongodb+srv://kushal:Blog123@navaidix.tmfd2mj.mongodb.net/blogApp?appName=Navaidix"