apiVersion: v1
kind: Secret
metadata:
  name: mongo-atlas-cred
  namespace: blog-app
type: Opaque
stringData:
  MONGO_URI: "mongodb+srv://kushal:Blog123@navaidix.tmfd2mj.mongodb.net/blogApp?retryWrites=true&w=majority&appName=Navaidix"
