name: CI Pipeline - Build Docker Images

on:
  push:
    branches: [ main ]  # Automatically runs on push to main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        run: |
          docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}

      - name: Build Backend Image
        run: |
          docker build -t kushalpichika/blog-backend:${{ github.sha }} ./Blog-api
          docker push kushalpichika/blog-backend:${{ github.sha }}

      - name: Build Frontend Image
        run: |
          docker build -t kushalpichika/blog-frontend:${{ github.sha }} ./Blog-frontend
          docker push kushalpichika/blog-frontend:${{ github.sha }}
